[package]
name = "nvml-rust"
description = "A rather basic exporter for nvidia graphics cards' metrics"
version = "0.1.0"
authors = ["Julius Michaelis <michaelis@jp.fujitsu.com>"]
edition = "2018"

[[bin]]
name = "nvml-prometheus-exporter"
path = "main.rs"

[profile.release]
#opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
nvml-wrapper = "0.5.0"
prometheus_exporter = "0.4.1"
prometheus = { version = "0.7.0", features = [ "process" ] }
structopt = "0.3.7"
lazy_static = "1.4.0"
